//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApplicationSystem.Services.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UAS_SystemEntities : DbContext
    {
        public UAS_SystemEntities()
            : base("name=UAS_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UAS_Applicants> UAS_Applicants { get; set; }
        public virtual DbSet<UAS_Household_Members> UAS_Household_Members { get; set; }
        public virtual DbSet<UAS_User_Details> UAS_User_Details { get; set; }
    }
}
