//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApplicationSystem.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAS_Applicants
    {
        public int AplicantId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AppStatus { get; set; }
    
        public virtual UAS_User_Details UAS_User_Details { get; set; }
    }
}
