//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApplicationSystem.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAS_Family_Relations
    {
        public int RelationId { get; set; }
        public Nullable<int> HId { get; set; }
        public string RelativeName { get; set; }
        public string RelationType { get; set; }
        public string ReverseRelationType { get; set; }
    
        public virtual UAS_Household_Members UAS_Household_Members { get; set; }
    }
}
