//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApplicationSystem.UserAccessService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccessData", Namespace="http://schemas.datacontract.org/2004/07/UserApplicationSystem.Services.DataContra" +
        "cts")]
    [System.SerializableAttribute()]
    public partial class UserAccessData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessageDataOfUserAccessDatajbgNRuBV", Namespace="http://schemas.datacontract.org/2004/07/UserApplicationSystem.Services.DataContra" +
        "cts")]
    [System.SerializableAttribute()]
    public partial class ResponseMessageDataOfUserAccessDatajbgNRuBV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserApplicationSystem.UserAccessService.UserAccessData DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserApplicationSystem.UserAccessService.UserAccessData Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserAccessService.IUserAccessService")]
    public interface IUserAccessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccessService/GetSignupInfo", ReplyAction="http://tempuri.org/IUserAccessService/GetSignupInfoResponse")]
        UserApplicationSystem.UserAccessService.ResponseMessageDataOfUserAccessDatajbgNRuBV GetSignupInfo(UserApplicationSystem.UserAccessService.UserAccessData signupInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccessService/GetSignupInfo", ReplyAction="http://tempuri.org/IUserAccessService/GetSignupInfoResponse")]
        System.Threading.Tasks.Task<UserApplicationSystem.UserAccessService.ResponseMessageDataOfUserAccessDatajbgNRuBV> GetSignupInfoAsync(UserApplicationSystem.UserAccessService.UserAccessData signupInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccessService/AuthenticateUser", ReplyAction="http://tempuri.org/IUserAccessService/AuthenticateUserResponse")]
        UserApplicationSystem.UserAccessService.ResponseMessageDataOfUserAccessDatajbgNRuBV AuthenticateUser(UserApplicationSystem.UserAccessService.UserAccessData loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccessService/AuthenticateUser", ReplyAction="http://tempuri.org/IUserAccessService/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<UserApplicationSystem.UserAccessService.ResponseMessageDataOfUserAccessDatajbgNRuBV> AuthenticateUserAsync(UserApplicationSystem.UserAccessService.UserAccessData loginInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserAccessServiceChannel : UserApplicationSystem.UserAccessService.IUserAccessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAccessServiceClient : System.ServiceModel.ClientBase<UserApplicationSystem.UserAccessService.IUserAccessService>, UserApplicationSystem.UserAccessService.IUserAccessService {
        
        public UserAccessServiceClient() {
        }
        
        public UserAccessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAccessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAccessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAccessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UserApplicationSystem.UserAccessService.ResponseMessageDataOfUserAccessDatajbgNRuBV GetSignupInfo(UserApplicationSystem.UserAccessService.UserAccessData signupInfo) {
            return base.Channel.GetSignupInfo(signupInfo);
        }
        
        public System.Threading.Tasks.Task<UserApplicationSystem.UserAccessService.ResponseMessageDataOfUserAccessDatajbgNRuBV> GetSignupInfoAsync(UserApplicationSystem.UserAccessService.UserAccessData signupInfo) {
            return base.Channel.GetSignupInfoAsync(signupInfo);
        }
        
        public UserApplicationSystem.UserAccessService.ResponseMessageDataOfUserAccessDatajbgNRuBV AuthenticateUser(UserApplicationSystem.UserAccessService.UserAccessData loginInfo) {
            return base.Channel.AuthenticateUser(loginInfo);
        }
        
        public System.Threading.Tasks.Task<UserApplicationSystem.UserAccessService.ResponseMessageDataOfUserAccessDatajbgNRuBV> AuthenticateUserAsync(UserApplicationSystem.UserAccessService.UserAccessData loginInfo) {
            return base.Channel.AuthenticateUserAsync(loginInfo);
        }
    }
}
